version: '3.3'
services:
  db:
    image: postgres:14.3-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=postgres

  frontend:
    image: drewnya/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

  web:
    image: drewnya/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/backend/static/
      - media_value:/app/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
