# Generated by Django 4.1 on 2022-08-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_cart_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Введите количество', verbose_name='Количество'),
        ),
    ]
